name: Synchronize

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,6,9,12,15 * * *'

jobs:
  sync:
    name: Synchronize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Post to Mastodon
        run: bin/publish --confirm --social=mastodon
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          LINK_API_KEY: ${{ secrets.LINK_API_KEY }}
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      - name: Post to Facebook
        run: bin/publish --confirm --social=facebook
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          LINK_API_KEY: ${{ secrets.LINK_API_KEY }}
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      - name: Post to Bluesky
        run: bin/publish --confirm --social=bluesky
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          LINK_API_KEY: ${{ secrets.LINK_API_KEY }}
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          commit_message: Update state file
          commit_user_name: 'dtinth-bot'
          commit_user_email: 'dtinth-bot@users.noreply.github.com'
      - name: Dump the new state
        if: always()
        run: cat state.yaml

permissions:
  contents: write
